---
title: '异步流程控制与错误处理'
date: '2018-07-12'
tags: ['Javascript']
categories: ['编程']
path: '/async-pattern-and-error-handling'
---

Javascript是一门天生有异步基因的语言，这是由于事件循环和浏览器的交互机制等原因决定的

对于异步流程的控制，我们经历了从最早的 callback，然后是 Promise，到现在的Async/Await和Generator，方式变得越来越灵活

```javascript
// 回调形式
getData(url1, a => {
    getData(url2, b => {
        getData(url3, c => {
            getData(url4, d => {
            	console.log(d);
            });
        });
    });
});
```

```javascript
// Promise形式
getData(url1)
.then(a => getData(url2))
.then(b => getData(url3))
.then(c => getData(url4))
.then(d => console.log(d));
```

```javascript
// Async/Await形式
(async () => {
    const a = await getData(url1);
    const b = await getData(url2);
    const c = await getData(url3);
    const d = await getData(url4);
    console.log(d);
})();
```

Async/Await 的缺点是不适用于并发的异步请求，我们可以结合Promise来解决这个问题，比如通过如下的代码实现：

```javascript
async function getAddress() {
    let [street, city, state, country] = 
        await Promise.all([getStreet(), getCity(), getState(), getCountry()]);
    return `${street}-${city}-${state}-${country}`;
}
```

对于上述这几种异步流程控制，Async/Await 也具有更优雅的错误处理方式：

```javascript
// Promise
const operate = () => {
    try {
        doSyncStuff();
        return getData().then(data => {
            data.map(item => item.doStuff());
        })
        .catch(e => console.log(e))
    } catch (e) {
        console.log(e);
    }
};
```

```javascript
// Async/Await
const operate = () => {
    try {
        doSyncStuff();
        const data = await getData();
        return data.map(item => item.doStuff());
    } catch (e) {
        console.log(e);
    }
};
```

如上，Promise 只能在catch中捕获错误，而Async/Await的形式下，可以像普通过程式的同步代码那样统一捕获和处理错误